# Generated by Django 4.2.2 on 2023-06-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="address",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="clinic",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="clinic",
            name="country",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="clinic",
            name="state",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
